#!/usr/bin/env python3
from pathlib import Path

root=Path(__file__).resolve().parents[1]
p=root/'Source/AERISFlightControl/UI/AERISNavigationDisplay.cs'
s=p.read_text(encoding='utf-8')

old='''        float cachedFallbackMapHeading;\n        string capturedBodyName = string.Empty;'''
new='''        float cachedFallbackMapHeading;\n        // Operation Health Pass 1 Hotfix 1: moving-map ownship symbology is committed\n        // on the exact Terrain FRONT swap, not on every IMGUI repaint. Terrain and the\n        // aircraft mark/range fan/track prediction therefore share one presentation frame.\n        long terrainSymbologyFrontSwap = -1L;\n        bool terrainSymbologyValid;\n        uint terrainSymbologyVesselPersistentId;\n        string terrainSymbologyBodyName = string.Empty;\n        double terrainSymbologyLatitudeDeg;\n        double terrainSymbologyLongitudeDeg;\n        double terrainSymbologyGroundSpeedMps;\n        double terrainSymbologyGroundTrackDeg;\n        string capturedBodyName = string.Empty;'''
if old not in s: raise SystemExit('field anchor not found')
s=s.replace(old,new,1)

old='''            pendingManualRangeMeters = float.NaN;\n            pendingManualRangeApplyRealtime = 0f;\n        }\n\n        internal void Dispose()'''
new='''            pendingManualRangeMeters = float.NaN;\n            pendingManualRangeApplyRealtime = 0f;\n            ResetTerrainSynchronizedSymbology();\n        }\n\n        internal void Dispose()'''
if old not in s: raise SystemExit('viewport reset anchor not found')
s=s.replace(old,new,1)

old='''            pendingManualRangeMeters = float.NaN;\n            pendingManualRangeApplyRealtime = 0f;\n        }\n\n        internal void Draw(Rect rect)'''
new='''            pendingManualRangeMeters = float.NaN;\n            pendingManualRangeApplyRealtime = 0f;\n            ResetTerrainSynchronizedSymbology();\n        }\n\n        internal void Draw(Rect rect)'''
if old not in s: raise SystemExit('dispose reset anchor not found')
s=s.replace(old,new,1)

old='''                bool terrainPresentationActive = planMode || !landActive || overlay;\n                if (terrainPresentationActive && terrainTileRenderer != null)\n                {\n                    AERISTerrainPresentedProjection presented =\n                        terrainTileRenderer.PresentedProjection;\n                    if (presented.Valid)\n                    {\n                        presentedCenterLatitudeDeg = presented.CenterLatitudeDeg;\n                        presentedCenterLongitudeDeg = presented.CenterLongitudeDeg;\n                        presentedRange = presented.RangeMeters;\n                        presentedHeading = presented.MapHeadingDeg;\n                        presentedTrackUp = presented.TrackUp;\n                        presentedAnchorV = presented.AnchorV;\n                    }\n                }\n\n                double ownEast = 0.0, ownNorth = 0.0;'''
new='''                bool terrainPresentationActive = planMode || !landActive || overlay;\n                AERISTerrainPresentedProjection presentedProjection =\n                    new AERISTerrainPresentedProjection();\n                if (terrainPresentationActive && terrainTileRenderer != null)\n                {\n                    presentedProjection = terrainTileRenderer.PresentedProjection;\n                    if (presentedProjection.Valid)\n                    {\n                        presentedCenterLatitudeDeg = presentedProjection.CenterLatitudeDeg;\n                        presentedCenterLongitudeDeg = presentedProjection.CenterLongitudeDeg;\n                        presentedRange = presentedProjection.RangeMeters;\n                        presentedHeading = presentedProjection.MapHeadingDeg;\n                        presentedTrackUp = presentedProjection.TrackUp;\n                        presentedAnchorV = presentedProjection.AnchorV;\n                    }\n                }\n                UpdateTerrainSynchronizedSymbology(vessel,\n                    terrainPresentationActive && !planMode, presentedProjection);\n                double displayOwnLatitudeDeg = terrainSymbologyValid ?\n                    terrainSymbologyLatitudeDeg : (vessel == null ? 0.0 : vessel.latitude);\n                double displayOwnLongitudeDeg = terrainSymbologyValid ?\n                    terrainSymbologyLongitudeDeg : (vessel == null ? 0.0 : vessel.longitude);\n\n                double ownEast = 0.0, ownNorth = 0.0;'''
if old not in s: raise SystemExit('presented projection anchor not found')
s=s.replace(old,new,1)

old='''                    ToLocalMeters(vessel.mainBody, frame.OriginLatitudeDeg,\n                        frame.OriginLongitudeDeg, vessel.latitude, vessel.longitude,\n                        out ownEast, out ownNorth);'''
new='''                    ToLocalMeters(vessel.mainBody, frame.OriginLatitudeDeg,\n                        frame.OriginLongitudeDeg, displayOwnLatitudeDeg,\n                        displayOwnLongitudeDeg, out ownEast, out ownNorth);'''
if old not in s: raise SystemExit('ownship map point anchor not found')
s=s.replace(old,new,1)

anchor='''        void UpdateAuxiliarySnapshots(Vessel vessel)\n        {'''
method='''        void ResetTerrainSynchronizedSymbology()\n        {\n            terrainSymbologyFrontSwap = -1L;\n            terrainSymbologyValid = false;\n            terrainSymbologyVesselPersistentId = 0u;\n            terrainSymbologyBodyName = string.Empty;\n            terrainSymbologyLatitudeDeg = 0.0;\n            terrainSymbologyLongitudeDeg = 0.0;\n            terrainSymbologyGroundSpeedMps = 0.0;\n            terrainSymbologyGroundTrackDeg = 0.0;\n        }\n\n        void UpdateTerrainSynchronizedSymbology(Vessel vessel, bool movingMapTerrainActive,\n            AERISTerrainPresentedProjection presented)\n        {\n            if (!movingMapTerrainActive || !presented.Valid || terrainTileRenderer == null ||\n                vessel == null || vessel.mainBody == null)\n            {\n                ResetTerrainSynchronizedSymbology();\n                return;\n            }\n            string bodyName = vessel.mainBody.name ?? string.Empty;\n            long frontSwap = terrainTileRenderer.FrontBufferSwaps;\n            if (terrainSymbologyValid && terrainSymbologyFrontSwap == frontSwap &&\n                terrainSymbologyVesselPersistentId == vessel.persistentId &&\n                string.Equals(terrainSymbologyBodyName, bodyName,\n                    StringComparison.OrdinalIgnoreCase)) return;\n\n            // In normal TERR moving-map mode the committed FRONT center is the ownship\n            // position used to build that terrain frame. Pin ownship to that exact committed\n            // geographic authority until the next FRONT swap; do not mix live vessel motion\n            // with an older terrain texture. Track and speed are captured on the same swap.\n            terrainSymbologyFrontSwap = frontSwap;\n            terrainSymbologyVesselPersistentId = vessel.persistentId;\n            terrainSymbologyBodyName = bodyName;\n            terrainSymbologyLatitudeDeg = presented.CenterLatitudeDeg;\n            terrainSymbologyLongitudeDeg = presented.CenterLongitudeDeg;\n            terrainSymbologyGroundSpeedMps = Math.Max(0.0, vessel.srfSpeed);\n            terrainSymbologyGroundTrackDeg = ResolveMapHeading(vessel);\n            terrainSymbologyValid = true;\n        }\n\n'''+anchor
if anchor not in s: raise SystemExit('auxiliary method anchor not found')
s=s.replace(anchor,method,1)

old='''            double ownEast, ownNorth;\n            ToLocalMeters(vessel.mainBody, centerLatitudeDeg, centerLongitudeDeg,\n                vessel.latitude, vessel.longitude, out ownEast, out ownNorth);\n\n            double speed = Math.Max(1.0, vessel.srfSpeed);\n            const double horizonSeconds = 60.0;\n            double distance = Math.Min(range * 0.42, speed * horizonSeconds);\n            double trackRad = cachedFallbackMapHeading * Math.PI / 180.0;'''
new='''            double ownLatitudeDeg = terrainSymbologyValid ?\n                terrainSymbologyLatitudeDeg : vessel.latitude;\n            double ownLongitudeDeg = terrainSymbologyValid ?\n                terrainSymbologyLongitudeDeg : vessel.longitude;\n            double ownEast, ownNorth;\n            ToLocalMeters(vessel.mainBody, centerLatitudeDeg, centerLongitudeDeg,\n                ownLatitudeDeg, ownLongitudeDeg, out ownEast, out ownNorth);\n\n            double speed = Math.Max(1.0, terrainSymbologyValid ?\n                terrainSymbologyGroundSpeedMps : vessel.srfSpeed);\n            const double horizonSeconds = 60.0;\n            double distance = Math.Min(range * 0.42, speed * horizonSeconds);\n            double displayTrackDeg = terrainSymbologyValid ?\n                terrainSymbologyGroundTrackDeg : cachedFallbackMapHeading;\n            double trackRad = displayTrackDeg * Math.PI / 180.0;'''
if old not in s: raise SystemExit('track vector anchor not found')
s=s.replace(old,new,1)

p.write_text(s,encoding='utf-8')
print('Operation Health Pass 1 Hotfix 1 symbology/front synchronization applied')
