#!/usr/bin/env python3
from pathlib import Path
import sys

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "Tools"

# AERIS23's Single-Authority tests intentionally asserted the then-literal
# terrainMaterial.SetPass(0). AERIS24 preserves the same one-SetPass/one-packed-draw
# authority but selects either the GPU exact material or the CPU fallback material via
# terrainDrawMaterial. Update only those inherited assertions; never relax draw count,
# painter order, legacy-mesh exclusion, or CPU fallback requirements.
selected_contract = """ck('Material terrainDrawMaterial = gpuEntry ?' in draw and
   'gpuVertexProjection.TerrainMaterial : terrainMaterial;' in draw and
   draw.count('terrainDrawMaterial.SetPass(0)') == 1 and
   draw.count('Graphics.DrawMeshNow(entry.PackedTerrainMesh, mapMatrix)') == 1 and
   'Graphics.DrawMeshNow(entry.LandMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.WaterMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.CoastalWaterCorrectionMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.CoastalLandCorrectionMesh, mapMatrix)' not in draw,
   'single packed terrain authority uses one selected CPU/GPU terrain SetPass and one packed draw per Entry')"""

known_old = """ck(draw.count('terrainMaterial.SetPass(0)') == 1 and
   draw.count('Graphics.DrawMeshNow(entry.PackedTerrainMesh, mapMatrix)') == 1 and
   'Graphics.DrawMeshNow(entry.LandMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.WaterMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.CoastalWaterCorrectionMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.CoastalLandCorrectionMesh, mapMatrix)' not in draw,
   'single packed terrain authority uses one terrain SetPass and one packed draw per Entry')"""

legacy_label = "'steady Entry terrain path is exactly one SetPass and one DrawMeshNow'"
legacy_label_new = "'steady Entry terrain path uses one selected CPU/GPU SetPass and one DrawMeshNow'"
legacy_generated_contract = """ck('Material terrainDrawMaterial = gpuEntry ?' in draw and
   'gpuVertexProjection.TerrainMaterial : terrainMaterial;' in draw and
   draw.count('terrainDrawMaterial.SetPass(0)') == 1 and
   draw.count('Graphics.DrawMeshNow(entry.PackedTerrainMesh, mapMatrix)') == 1 and
   'Graphics.DrawMeshNow(entry.LandMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.WaterMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.CoastalWaterCorrectionMesh, mapMatrix)' not in draw and
   'Graphics.DrawMeshNow(entry.CoastalLandCorrectionMesh, mapMatrix)' not in draw,
   'steady Entry terrain path uses one selected CPU/GPU SetPass and one DrawMeshNow')"""

patched = []
already = []
for path in sorted(TOOLS.glob("*.py")):
    try:
        text = path.read_text()
    except Exception:
        continue
    original = text

    # Pass3 projection/draw-reduction assertion produced by the AERIS23 fix chain.
    if known_old in text:
        text = text.replace(known_old, selected_contract, 1)
    elif selected_contract in text:
        already.append(path.name)

    # The dedicated Single-Authority suite is generated by the candidate applicator and
    # has a different label. Replace exactly the ck(...) containing that unique label,
    # regardless of the generated filename, so the test follows the successor contract.
    if legacy_label in text:
        label_at = text.index(legacy_label)
        start = text.rfind("ck(", 0, label_at)
        end = text.find(")", label_at)
        if start < 0 or end < 0:
            raise SystemExit("[AERIS24 GPU VERTEX TEST FIX] malformed generated Single-Authority check in " + path.name)
        end += 1
        stale_block = text[start:end]
        if "PackedTerrainMesh" not in stale_block or "SetPass(0)" not in stale_block:
            raise SystemExit("[AERIS24 GPU VERTEX TEST FIX] refusing unexpected generated check in " + path.name)
        text = text[:start] + legacy_generated_contract + text[end:]
    elif legacy_label_new in text:
        already.append(path.name)

    if text != original:
        path.write_text(text)
        patched.append(path.name)

if not patched and not already:
    raise SystemExit("[AERIS24 GPU VERTEX TEST FIX] no inherited Single-Authority SetPass assertion found")

for name in patched:
    print("[AERIS24 GPU VERTEX TEST FIX] patched " + name)
for name in sorted(set(already)):
    print("[AERIS24 GPU VERTEX TEST FIX] already successor-aware " + name)
print("[AERIS24 GPU VERTEX TEST FIX] PASS")
print("Contract: selected CPU/GPU terrain material -> exactly one SetPass + one PackedTerrainMesh draw + zero legacy terrain draws")
