#!/usr/bin/env python3
import re,sys
from pathlib import Path
sys.dont_write_bytecode=True
from v01700_testlib import ROOT,SOURCE,CheckSuite,read
suite=CheckSuite('v0.18.0.0 CP3.5 Gate 3 CP3 Frozen Visual Path Recovery / Bounded Exact Refinement Candidate 2')
renderer=read(SOURCE/'Terrain/AERISTerrainGpuTileRenderer.cs')
virtual=read(SOURCE/'Terrain/AERISTerrainVirtualDetail.cs')
tiles=read(SOURCE/'Terrain/AERISTerrainTileSystem.cs')
contracts=read(SOURCE/'Terrain/AERISTerrainTileContracts.cs')
perf=read(SOURCE/'Terrain/AERISTerrainPerformance.cs')
settings=read(SOURCE/'Settings/AERISSettings.cs')
window=read(SOURCE/'UI/AERISWindow.cs')
nd=read(SOURCE/'UI/AERISNavigationDisplay.cs')
version=read(SOURCE/'Properties/AERISBuildVersion.generated.cs')
build=read(ROOT/'build_ubuntu.sh')
avc=read(ROOT/'GameData/AERISFlightControl/AERISFlightControl.version')
identity='DEV CP3.5 GATE 3 — CP3 FROZEN VISUAL PATH RECOVERY / BOUNDED EXACT REFINEMENT CANDIDATE 2'
hotfix_identity=identity+' — PRESENTATION AUTHORITY HOTFIX 1'
build_hotfix_identity=hotfix_identity+' — BUILD ENTRYPOINT HOTFIX 2'
suite.check(any('internal const string UiCheckpoint = \"'+x+'\"' in version for x in (identity,hotfix_identity,build_hotfix_identity)),'generated Candidate 2 lineage identity')
suite.check(any('internal const string UiCheckpoint = \"'+x+'\"' in build for x in (identity,hotfix_identity,build_hotfix_identity)),'build Candidate 2 lineage identity')
suite.check('CP3 FROZEN VISUAL PATH RECOVERY BOUNDED EXACT REFINEMENT CANDIDATE 2' in build,'build display identity')
suite.check('Gate 3 CP3 Frozen Visual Path Recovery / Bounded Exact Refinement Candidate 2' in avc,'AVC Candidate 2 lineage identity')
suite.check(('run_v01800_cp35_gate3_candidate2_acceptance.py' in build) or ('run_v01800_cp35_gate3_candidate2_presentation_authority_hotfix1_acceptance.py' in build),'build invokes Candidate 2 lineage acceptance')

# Candidate 1 generated hi-res path must be impossible from the live viewport.
suite.check('AddAdaptiveExactDetailBridge' not in tiles,'generated adaptive exact viewport bridge removed')
suite.check('AddExistingExactDetailBridge(latitude, longitude, nearLod' in tiles,'existing-only exact bridge restored')
suite.check('if (!ExactDetailPayloadExists(key)) continue;' in tiles,'missing Route/Local exact payload is never generated by viewport bridge')
suite.check('radius = Math.Max(0, Math.Min(1, requestedRadius))' in tiles,'existing exact bridge remains bounded to radius <= 1')
suite.check('range <= 10000.0 ? AERISTerrainTileLod.Local' in tiles,'frozen near-LOD local threshold restored')
suite.check('range <= 40000.0 ? AERISTerrainTileLod.Route : AERISTerrainTileLod.Far' in tiles,'frozen near-LOD FAR above 40 km restored')
suite.check('range <= 160000.0 ? AERISTerrainTileLod.Route' not in tiles,'Candidate 1 160 km Route promotion removed')

# Golden CP3 virtual-detail path.
suite.check('"FAR DIRECT", 1, 33, 1.0f' in virtual,'CP3 FAR direct profile restored')
suite.check('"VIRTUAL ROUTE", 2, 65, 1.25f' in virtual,'CP3 virtual Route profile restored')
suite.check('"VIRTUAL LOCAL", 3, 97, 1.50f' in virtual,'CP3 virtual Local profile restored')
suite.check('targetCellPixels' not in virtual and 'viewportPixels' not in virtual,'Candidate 1 screen-space hi-res policy removed')
suite.check('landScore >= 0.5f ? (byte)1 : (byte)2' not in virtual,'Candidate 1 synthetic coastline class interpolation removed')
suite.check('NearestClassHeight' in virtual and 'sameClass' in virtual,'CP3 conservative coastline reconstruction restored')
suite.check('ResolveVirtualDetailProfile(rangeMeters)' in renderer,'renderer uses frozen range-only virtual detail')
suite.check('AERISTerrainVirtualDetailPolicy.Resolve(quality, rangeMeters);' in renderer,'renderer invokes frozen CP3 virtual-detail policy')

# Known-good CP3/Gate2 performance envelope, not Candidate 1 widened working set.
suite.check('48, 1, 3, 720f, 32, 1.25f, AERISTerrainTileLod.Local, 256, 2048, 192' in perf,'HIGH profile restored to bounded CP3/Gate2 envelope')
suite.check('56, 2, 4, 960f, 40, 1.45f' not in perf,'Candidate 1 widened HIGH envelope removed')
suite.check(perf.count('new AERISTerrainPerformanceProfile(')==3,'only LOW/MEDIUM/HIGH explicit profiles remain')

# Terrain-quality LAND remains fully retired while LAND autopilot remains independent.
retired=['AERISTerrainQualityMode.Land','AERISTerrainTileLod.Land','TerrainLandRuntimeQualityEnabled','AERISTerrainLandDetailActivationPolicy','AERISTerrainRequestLane.Landing','new AERISTerrainPerformanceProfile("LAND"']
allcs='\n'.join(read(p) for p in SOURCE.rglob('*.cs'))
for token in retired: suite.check(token not in allcs,'retired terrain-quality token absent: '+token)
suite.check(not (SOURCE/'Terrain/AERISTerrainLandDetailActivationPolicy.cs').exists(),'retired terrain LAND policy source absent')
suite.check('new string[]{"AUTO","LOW","MEDIUM","HIGH"}' in window,'quality selector remains AUTO/LOW/MEDIUM/HIGH only')
suite.check('string[] labels={"TAKEOFF","FLIGHT","NAV","LAND"}' in window,'AUTOPILOT LAND category remains intact')
suite.check('NavigationDisplayLandProfileSize' in settings and 'DrawLandingProfile' in nd,'LAND guidance display remains intact')

# CP3.5 multicore / exact keyframe / temporal path retained.
suite.check('HistoryOverscanScale = 1.25f' in renderer,'overscan history retained')
suite.check('TemporalMaximumErrorPixels = 0.75f' in renderer,'sub-pixel temporal confidence retained')
suite.check('ProjectionBatch' in renderer and 'ProjectionChunkResult' in renderer,'multicore projection batches retained')
suite.check('CancelProjectionBatch();' in renderer,'worker cancellation boundary retained')
suite.check('GUI.matrix =' not in renderer and 'GUI.matrix=' not in renderer,'GUI.matrix temporal warp remains prohibited')
suite.check('static bool DrawPreparedEntry(' not in renderer,'Compile Hotfix 1 static material regression absent')
suite.check(re.search(r'\n\s*bool DrawPreparedEntry\(Entry entry, Matrix4x4 mapMatrix,',renderer) is not None,'DrawPreparedEntry remains instance method')

# Accessibility fixes and unified world surface are retained but may not trigger hi-res generation.
suite.check('new Color32(70, 84, 92, 255)' in renderer,'HIGH safe terrain no longer near-black')
suite.check('new Color32(220, 125, 215, 255)' in renderer,'BY caution avoids white saturation')
suite.check('new Color32(82, 96, 108, 255)' in renderer,'RG safe terrain remains sea-distinct')
suite.check('new Color32(0, 20, 12, 255)' not in renderer,'old HIGH near-black removed')
suite.check('new Color32(242, 235, 225, 255)' not in renderer,'old BY near-white removed')
suite.check('HandlePaletteGeneration(currentPreset);' in renderer,'palette generation invalidation retained')
suite.check('SetWorldSurfaceNavigationFrame(AERISPreparedNavigationFrame frame' in renderer,'unified world surface phase 1 retained')
suite.check('DrawWorldSurfaceNavigation(batch, detailedProfile, ref profile);' in renderer,'world navigation surface composition retained')

# UI requirements retained.
suite.check('ResponsiveWidth' in window and 'CompactControlHeight' in window,'responsive compact UI retained')
suite.check('wordWrap=false' in window or 'wordWrap = false' in window,'automatic text wrapping remains disabled')
suite.check('TopTabGap=2f' in window,'symmetric compact top-row geometry retained')

# Static enum reference guard.
def enum_members(text,name):
    m=re.search(r'internal\s+enum\s+'+re.escape(name)+r'\s*\{([^}]*)\}',text,re.S)
    return set() if not m else {x.split('=',1)[0].strip() for x in m.group(1).split(',') if x.split('=',1)[0].strip()}
for enum_name,text in [('AERISTerrainTileLod',contracts),('AERISTerrainRequestLane',contracts),('AERISTerrainQualityMode',settings)]:
    members=enum_members(text,enum_name); refs=set(re.findall(re.escape(enum_name)+r'\.([A-Za-z_][A-Za-z0-9_]*)',allcs)); unknown=sorted(refs-members)
    suite.check(not unknown,enum_name+' references resolve to declared members',', '.join(unknown))

suite.check((ROOT/'ACCEPTANCE_v0.18.0.0_CP3.5_GATE3_CP3_FROZEN_VISUAL_PATH_RECOVERY_BOUNDED_EXACT_REFINEMENT_CANDIDATE2.txt').is_file(),'acceptance contract included')
suite.check((ROOT/'Docs/ND_CP3.5_GATE3_CP3_FROZEN_VISUAL_PATH_RECOVERY_CANDIDATE2_TEST_CARD_v0.18.0.0_ja.md').is_file(),'runtime test card included')
suite.check((ROOT/'Docs/CP3.5_GATE3_CP3_FROZEN_VISUAL_PATH_RECOVERY_CANDIDATE2_DESIGN_ja.md').is_file(),'design note included')
suite.finish()
