#!/usr/bin/env python3
import re,sys
from pathlib import Path
sys.dont_write_bytecode=True
from v01700_testlib import ROOT,SOURCE,CheckSuite,read,strip_csharp_comments_and_literals
suite=CheckSuite('v0.18.0.0 CP3.5 Gate 3 Sparse Hi-Res / Palette V2 / Archive Retention Candidate 3')
renderer=read(SOURCE/'Terrain/AERISTerrainGpuTileRenderer.cs')
virtual=read(SOURCE/'Terrain/AERISTerrainVirtualDetail.cs')
coast=read(SOURCE/'Terrain/AERISTerrainCoastlinePolicy.cs')
raster=read(SOURCE/'Terrain/AERISTerrainGpuTileRasterizer.cs')
tiles=read(SOURCE/'Terrain/AERISTerrainTileSystem.cs')
settings=read(SOURCE/'Settings/AERISSettings.cs')
window=read(SOURCE/'UI/AERISWindow.cs')
archive=read(SOURCE/'Recording/AERISFlightDataArchive.cs')
bootstrap=read(SOURCE/'Core/AERISBootstrap.cs')
config=read(ROOT/'GameData/AERISFlightControl/Config/AERISSettings.cfg')
version=read(SOURCE/'Properties/AERISBuildVersion.generated.cs')
build=read(ROOT/'build_ubuntu.sh')
avc=read(ROOT/'GameData/AERISFlightControl/AERISFlightControl.version')
identity='DEV CP3.5 GATE 3 — SPARSE HI-RES / PALETTE V2 / ARCHIVE RETENTION CANDIDATE 3'
suite.check('internal const string UiCheckpoint = "'+identity+'"' in version,'generated Candidate 3 identity')
suite.check('internal const string UiCheckpoint = "'+identity+'"' in build,'build Candidate 3 identity')
suite.check('Sparse Hi-Res / Palette V2 / Archive Retention Candidate 3' in avc,'AVC Candidate 3 identity')
# Safety boundary: no Candidate 1 all-visible generated promotion.
suite.check('AddAdaptiveExactDetailBridge' not in tiles,'all-visible generated exact bridge remains removed')
suite.check('AddExistingExactDetailBridge(latitude, longitude, nearLod' in tiles,'bounded existing-only exact refinement retained')
suite.check('if (!ExactDetailPayloadExists(key)) continue;' in tiles,'missing Route/Local payload is not generated by viewport')
suite.check('radius = Math.Max(0, Math.Min(1, requestedRadius))' in tiles,'exact refinement radius remains <=1')
# Long range geometry stays FAR; HIGH gets only denser presentation surface, not multiplied Unity meshes.
suite.check('"FAR DIRECT", 1, 33, 1.0f' in virtual,'FAR 33x33 safety foundation retained')
suite.check('"FAR DIRECT HI-DPI", 1, 33, 1.25f' in virtual,'HIGH long-range Hi-DPI surface added without geometry promotion')
suite.check('if (high) return FarDirectHighDpi;' in virtual,'HIGH long range selects Hi-DPI FAR surface')
suite.check('range <= 160000.0 ? AERISTerrainTileLod.Route' not in tiles,'160 km exact Route mass-promotion remains forbidden')
# Subcell coastline uses endpoint elevations at ocean surface in both pre-raster and renderer fill paths.
suite.check('OceanSurfaceMeters = 1.0f' in coast,'coastline uses authoritative ocean surface threshold')
suite.check('CrossingFraction(bool water0, bool water1,\n            float elevation0Meters, float elevation1Meters)' in coast,'elevation-aware subcell coastline crossing exists')
suite.check('AERISTerrainCoastlinePolicy.CrossingFraction(water0, water1,\n                elevation0, elevation1)' in raster,'raster coastline passes endpoint elevations')
suite.check('AERISTerrainCoastlinePolicy.CrossingFraction(a.Water, b.Water,' in renderer and 'a.ElevationMeters, b.ElevationMeters' in renderer,'renderer coastline fill shares subcell crossing policy')
# Palette V2 dynamically spends its range on visible terrain and avoids previous pathological endpoints.
suite.check('TopographicWindowBucketMeters = 250f' in renderer,'TOPO window uses stable 250m buckets')
suite.check('TopographicMinimumSpanMeters = 1500f' in renderer,'TOPO window guarantees useful local contrast span')
suite.check('ResolveTopographicWindow(tiles, out topoMinimumMeters, out topoMaximumMeters);' in renderer,'visible terrain drives TOPO normalization')
suite.check('(terrainAltitudeMeters + 500f) / 12500f' not in renderer,'fixed 12.5km TOPO normalization removed')
for bad in ('new Color32(0, 20, 12, 255)','new Color32(242, 235, 225, 255)'):
    suite.check(bad not in renderer,'pathological accessibility endpoint removed: '+bad)
suite.check('new Color32(76, 78, 82, 255)' in renderer and 'new Color32(220, 222, 214, 255)' in renderer,'HIGH contrast palette has bounded luminance endpoints')
suite.check('HandlePaletteGeneration(currentPreset);' in renderer,'palette generation invalidation retained')
# Exact authority stays hard; temporal shadow per-frame grid is disabled during recovery.
suite.check('const bool TemporalShadowSamplingEnabled = false;' in renderer,'temporal shadow grid disabled for exact-authority performance')
suite.check('TryBuildRefreshMetrics' in renderer,'cheap exact-front refresh metrics replace per-frame temporal grid')
suite.check('const bool TemporalPresentationAuthorityEnabled = false;' in renderer,'temporal presentation remains quarantined')
suite.check('PresentFrontDirect(plot, frontOrientation)' in renderer,'Exact FRONT direct authority retained')
suite.check('GUI.matrix =' not in renderer and 'GUI.matrix=' not in renderer,'GUI.matrix temporal warp remains prohibited')
# FDR/CVR retention contract.
suite.check('internal int FlightDataArchiveLimit = 10;' in settings,'archive limit defaults to 10')
suite.check('Math.Max(1, Math.Min(30, value))' in settings,'archive setting clamped to 1..30')
suite.check('"flightDataArchiveLimit"' in settings and 'node.AddValue("flightDataArchiveLimit"' in settings,'archive limit load/save persisted')
suite.check('FlightArchiveLimitLabels' in window and '"30"' in window,'UI exposes 1..30 selection labels')
suite.check('GUILayout.SelectionGrid(current,FlightArchiveLimitLabels,10' in window,'archive limit is selection-only 30-option UI')
suite.check('AERISFlightDataArchive.ConfigureRetention(next)' in window,'UI applies archive retention immediately')
suite.check('AERISFlightDataArchive.ConfigureRetention(settings.FlightDataArchiveLimit);' in bootstrap,'startup applies persisted archive limit')
suite.check('VerifiedMarkerSuffix = ".verified"' in archive,'only marked verified ZIPs are retention candidates')
suite.check('File.Exists(path + VerifiedMarkerSuffix)' in archive,'unverified ZIPs excluded from pruning')
suite.check('SearchOption.TopDirectoryOnly' in archive,'retention cannot descend into active/raw flight folders')
suite.check('string.Equals(normalized, current' in archive,'newly committed current archive excluded from deletion pass')
suite.check('LastWriteUtc.CompareTo' in archive,'verified ZIP pruning is oldest-first')
suite.check('unverified ZIP/raw/tmp entries untouched' in archive,'retention safety detail explicit')
suite.check('flightDataArchiveLimit = 10' in config,'default CFG archive limit is 10')
# Terrain quality LAND is fully retired; AP LAND remains.
allcs='\n'.join(read(p) for p in SOURCE.rglob('*.cs'))
for token in ('AERISTerrainQualityMode.Land','TerrainLandRuntimeQualityEnabled','AERISTerrainRequestLane.Landing','AERISTerrainLandDetailActivationPolicy'):
    suite.check(token not in allcs,'retired terrain-quality token absent: '+token)
suite.check('terrainLandRuntimeQualityEnabled' not in config,'retired LAND quality cfg key absent')
suite.check('new string[]{"AUTO","LOW","MEDIUM","HIGH"}' in window,'terrain quality UI has exactly four current presets')
suite.check('string[] labels={"TAKEOFF","FLIGHT","NAV","LAND"}' in window,'AUTOPILOT LAND category remains independent')
# Syntax-level balance for modified dense files.
for label,text in [('renderer',renderer),('archive',archive),('window',window)]:
    clean=strip_csharp_comments_and_literals(text)
    suite.check(clean.count('{')==clean.count('}'),label+' braces balanced')
    suite.check(clean.count('(')==clean.count(')'),label+' parens balanced')
suite.check((ROOT/'ACCEPTANCE_v0.18.0.0_CP3.5_GATE3_SPARSE_HIRES_PALETTE_V2_ARCHIVE_RETENTION_CANDIDATE3.txt').is_file(),'Candidate 3 acceptance contract included')
suite.check((ROOT/'Docs/CP3.5_GATE3_SPARSE_HIRES_PALETTE_V2_ARCHIVE_RETENTION_CANDIDATE3_DESIGN_ja.md').is_file(),'Candidate 3 design note included')
suite.check((ROOT/'Docs/ND_CP3.5_GATE3_SPARSE_HIRES_PALETTE_V2_ARCHIVE_RETENTION_CANDIDATE3_TEST_CARD_v0.18.0.0_ja.md').is_file(),'Candidate 3 runtime test card included')
suite.finish()
